env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:vue/recommended']

parserOptions:
  ecmaFeatures:
    vue: true
  ecmaVersion: 6
  sourceType: module

plugins: ['vue']

settings:
  vue:
    version: '2'
